<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="E053599-VM2" name="test.cases.TimeandLabour.CR4355_Functional.E150_CR4355_CreateAdditionalAssignmentTest" tests="1" failures="1" timestamp="26 Feb 2019 04:09:32 GMT" time="71.174" errors="0">
  <testcase name="E150_CR4355_01_Test" time="71.174" classname="test.cases.TimeandLabour.CR4355_Functional.E150_CR4355_CreateAdditionalAssignmentTest">
    <failure type="java.lang.AssertionError" message="******Job Informtion  Failed   *****">
      <![CDATA[java.lang.AssertionError: ******Job Informtion  Failed   *****
	at processes.HR.AddAdditionalAssignmentProcess.JobInformtion_CR4355(AddAdditionalAssignmentProcess.java:168)
	at test.cases.TimeandLabour.CR4355_Functional.E150_CR4355_CreateAdditionalAssignmentTest.E150_CR4355_01_Test(E150_CR4355_CreateAdditionalAssignmentTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- E150_CR4355_01_Test -->
</testsuite> <!-- test.cases.TimeandLabour.CR4355_Functional.E150_CR4355_CreateAdditionalAssignmentTest -->
