<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="E053599-VM2" name="test.cases.TimeandLabour.CR4355_Functional.E150_CR4355_01_CopyS34relationshipOnActingRecordWithUnapprovedtimeTest" tests="1" failures="0" timestamp="7 Mar 2019 19:10:17 GMT" time="12.290" errors="1">
  <testcase name="E150_CR4355_01_Test" time="12.290" classname="test.cases.TimeandLabour.CR4355_Functional.E150_CR4355_01_CopyS34relationshipOnActingRecordWithUnapprovedtimeTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pages.objects.Common_Obj.Navigation_MenuLink(Common_Obj.java:101)
	at pages.common.actions.Common_Action.NAVS_TimeReporterStatus(Common_Action.java:167)
	at test.cases.TimeandLabour.CR4355_Functional.E150_CR4355_01_CopyS34relationshipOnActingRecordWithUnapprovedtimeTest.navigateToTimeReporterPage(E150_CR4355_01_CopyS34relationshipOnActingRecordWithUnapprovedtimeTest.java:118)
	at test.cases.TimeandLabour.CR4355_Functional.E150_CR4355_01_CopyS34relationshipOnActingRecordWithUnapprovedtimeTest.E150_CR4355_01_Test(E150_CR4355_01_CopyS34relationshipOnActingRecordWithUnapprovedtimeTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- E150_CR4355_01_Test -->
</testsuite> <!-- test.cases.TimeandLabour.CR4355_Functional.E150_CR4355_01_CopyS34relationshipOnActingRecordWithUnapprovedtimeTest -->
